proxy_url = '127.0.0.1:7890'

urls = [
  # https://www.pornhub.com/categories

  # "https://www.pornhub.com/video?o=tr",
  # "https://www.pornhub.com/video?o=ht",
  "https://www.pornhub.com/video?o=mv",
]
